module.exports = ( { env } ) => ( {
	plugins: {
		'postcss-import': {},
		'postcss-for': {},
		'postcss-each': {},
		'postcss-mixins': {},
		'postcss-extend': {},
		'postcss-nested-ancestors': {},
		'postcss-nested': {},
		'postcss-css-variables': {},
		'postcss-custom-selectors': {},
		'postcss-custom-media': {},
		'postcss-if-media': {},
		'postcss-quantity-queries': {},
		'postcss-start-to-end': {},
		'postcss-calc': {},
		'postcss-size': {},
		'postcss-position': {},
		'postcss-transform-shortcut': {},
		'postcss-selector-not': {},
		'postcss-combine-media-query': {},
		autoprefixer: {},
	},
} );
